#Sass-Lint settings based on Sass Guidelines (https://sass-guidelin.es/)
options:
  formatter: stylish
  merge-default-rules: false

rules:
  bem-depth:
    - 2
    - max-depth: 1
  #Fixed after conversion
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: >-
        ^(?:u|is|has)\-[a-z][a-zA-Z0-9]*$|^(?!u|is|has)[a-zA-Z][a-zA-Z0-9]*(?:\-[a-z][a-zA-Z0-9]*)?(?:\-\-[a-z][a-zA-Z0-9]*)?$
  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  id-name-format:
    - 2
    - convention: hyphenatedlowercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  mixin-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 2
  nesting-depth:
    - 2
    - max-depth: 1
  no-color-keywords: 2
  #Change deviating from styleguide
  no-color-literals: 2
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 0
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 0
  no-misspelled-properties:
    - 2
    - extra-properties: []
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-transition-all: 0
  no-url-protocols: 0
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
  property-sort-order: 0
  #Change deviating from styleguide
  property-units:
    - 2
    - global:
      - rem
      per-property:
        border:
          - px
        border-top:
          - px
        border-right:
          - px
        border-bottom:
          - px
        border-left:
          - px
        border-radius:
          - px
        box-shadow:
          - px
  quotes:
    - 2
    - style: single
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma: 2
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 2
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 0
  variable-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 2